pkgs:
[
    pkgs.cantarell-fonts
    pkgs.emacs-all-the-icons-fonts
    pkgs.font-awesome
    pkgs.hasklig
    pkgs.iosevka
    pkgs.source-code-pro
    pkgs.texlive.combined.scheme-full
    pkgs.nerdfonts
  ]
