# nvfetcher.toml
[fish-abbreviation-tips]
src.git = "https://github.com/gazorby/fish-abbreviation-tips"
fetch.github = "gazorby/fish-abbreviation-tips"

[fzf.fish]
src.git = "https://github.com/PatrickF1/fzf.fish"
fetch.github = "PatrickF1/fzf.fish"

[jethrokuan-z]
src.git = "https://github.com/jethrokuan/z"
fetch.github = "jethrokuan/z"

[nvmfish]
src.git = "https://github.com/jorgebucaran/nvm.fish"
fetch.github = "jorgebucaran/nvm.fish"

[replayfish]
src.git = "https://github.com/jorgebucaran/replay.fish"
fetch.github = "jorgebucaran/replay.fish"

[rsync-bpc]
src.git = "https://github.com/backuppc/rsync-bpc"
fetch.github = "backuppc/rsync-bpc"
